#!/usr/bin/env python
import argparse
import os

parser = argparse.ArgumentParser()
parser.add_argument("--log", nargs="?", default="WARNING")
parser.add_argument("--report", nargs=1, default="tracked-shared-ptrs")
parser.add_argument("command", nargs="+")
args = parser.parse_args()
command = ["gdb",
           "-batch",
           "-ex", "source " + __file__ + ".py",
           "-ex", "python-log-level " + args.log,
           "-ex", "track-shared-ptrs " + args.report,
           "--args"] + args.command
os.execvp(command[0], command)
